# Generated by Django 5.0.6 on 2026-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('panaderia', 'Panadería'), ('pasteleria', 'Pastelería'), ('bebida', 'Bebida'), ('chucheria', 'Chuchería'), ('recurso', 'Recurso pastelero')], default='panaderia', max_length=20),
        ),
    ]
