# Generated by Django 5.0.6 on 2026-05-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sabor',
            field=models.BooleanField(default=False, verbose_name='sabor'),
        ),
    ]
