# Generated by Django 5.0.6 on 2026-05-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0003_producto_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panaderia_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('Harina', 'Harina'), ('Mantequilla', 'Mantequilla'), ('Margarina', 'Margarina'), ('Huevos', 'Huevos'), ('Levadura', 'Levadura'), ('Azucar', 'Azucar'), ('Sal', 'Sal')], default='Harina', max_length=20, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Bultos restantes')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaderia.marca', verbose_name='Marca')),
            ],
        ),
    ]
