# Generated by Django 6.0.6 on 2026-06-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0004_panaderia_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='panaderia_items',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Bultos restantes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('pan_salado', 'Pan Salado'), ('pan_dulce', 'Pan Dulce'), ('pasteleria', 'Pastelería'), ('bebida', 'Bebida'), ('chucheria', 'Chuchería'), ('recurso', 'Recurso')], default='pan_salado', max_length=20),
        ),
    ]
