# Generated by Django 6.0.6 on 2026-06-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0005_producto_stock_alter_panaderia_items_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaItem',
        ),
    ]
