# Generated by Django 6.0.6 on 2026-06-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0006_remove_ventaitem_venta_remove_ventaitem_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
