# Generated by Django 6.0.6 on 2026-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0007_remove_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('panaderia', 'Panadería'), ('bebida', 'Bebidas'), ('chucheria', 'Chucherías'), ('recurso', 'Recursos')], default='panaderia', max_length=20),
        ),
    ]
