# Generated by Django 6.0.6 on 2026-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0012_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='target_date',
            field=models.DateField(blank=True, help_text='Fecha a la que corresponde el snapshot de inventario, si aplica', null=True),
        ),
    ]
