# Generated by Django 6.0.6 on 2026-07-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0013_backup_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración personalizada del usuario', null=True),
        ),
    ]
