# Generated by Django 6.0.6 on 2026-07-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0014_profile_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panaderia_items',
            options={'verbose_name': 'Insumo de materia prima', 'verbose_name_plural': 'Insumos de materia prima'},
        ),
        migrations.AddField(
            model_name='panaderia_items',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('ud', 'Unidades')], default='kg', help_text='Unidad en la que se registra la cantidad del insumo.', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='panaderia_items',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad disponible del insumo en la unidad seleccionada.', max_digits=10, verbose_name='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='panaderia_items',
            name='marca',
            field=models.ForeignKey(help_text='Marca del insumo de materia prima.', on_delete=django.db.models.deletion.CASCADE, to='panaderia.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='panaderia_items',
            name='tipo_item',
            field=models.CharField(help_text='Describa el insumo de materia prima que se guardará en el inventario.', max_length=100, verbose_name='Insumo de materia prima'),
        ),
    ]
