# Generated by Django 6.0.6 on 2026-07-05 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0015_alter_panaderia_items_options_panaderia_items_unidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=150, verbose_name='Empleado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo de empleado',
                'verbose_name_plural': 'Insumos de empleados',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
