# Generated by Django 6.0.6 on 2026-07-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0016_employeeinsumo_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='panaderia_items',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock separado del peso o volumen. Indica cuántas unidades hay disponibles.', verbose_name='Stock disponible'),
        ),
    ]
