# Generated by Django 6.0.6 on 2026-07-05 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0017_panaderia_items_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'verbose_name': 'Backup', 'verbose_name_plural': 'Backups'},
        ),
        migrations.AlterModelOptions(
            name='bebida',
            options={'verbose_name': 'Bebida', 'verbose_name_plural': 'Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='chucheria',
            options={'verbose_name': 'Chuchería', 'verbose_name_plural': 'Chucherías'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventaitem',
            options={'verbose_name': 'Item de venta', 'verbose_name_plural': 'Items de venta'},
        ),
        migrations.AlterField(
            model_name='bebida',
            name='volumen_ml',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Volumen (ml)'),
        ),
        migrations.AlterField(
            model_name='chucheria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='employeeinsumo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('panaderia', 'Panadería'), ('bebida', 'Bebidas'), ('chucheria', 'Chucherías'), ('recurso', 'Recursos')], default='panaderia', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='panaderia_items',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible del insumo en la unidad seleccionada.', max_digits=10, verbose_name='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('pan_salado', 'Pan Salado'), ('pan_dulce', 'Pan Dulce'), ('pasteleria', 'Pastelería'), ('bebida', 'Bebida'), ('chucheria', 'Chuchería'), ('recurso', 'Recurso')], default='pan_salado', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sabor',
            field=models.BooleanField(default=False, verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos colombianos'), ('VES', 'Bolívares venezolanos'), ('USD', 'Dólares')], default='COP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos colombianos'), ('VES', 'Bolívares venezolanos'), ('USD', 'Dólares')], default='COP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario'),
        ),
    ]
