# Generated by Django 6.0.6 on 2026-07-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0018_alter_backup_options_alter_bebida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='entrada_manana',
            field=models.PositiveIntegerField(default=0, verbose_name='Entrada mañana'),
        ),
        migrations.AddField(
            model_name='producto',
            name='entrada_tarde',
            field=models.PositiveIntegerField(default=0, verbose_name='Entrada tarde'),
        ),
        migrations.AddField(
            model_name='producto',
            name='existencia_manana',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencia mañana'),
        ),
    ]
