# Generated by Django 6.0.6 on 2026-07-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0019_producto_entrada_manana_producto_entrada_tarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pago_movil', 'Pago móvil'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
